---
title: Scratch ओलंपिक धावक
hero_image: images/banner.png
description: स्क्रैच में एक हर्डलर गेम
original_url: https://raspberrypi.org/learning/scratch-olympics-hurdler
theme: नारंगी
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: प्रोजेक्ट
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: आपको किसकी ज़रूरत होगी
  - 
    title: परियों को पकड़ना
  - 
    title: सामग्री सेट अप करना
  - 
    title: Key mashing (कुंजी मैशिंग) को कैप्चर करना
  - 
    title: धावक को एनिमेट करना
  - 
    title: जंपिंग (कूदना)
  - 
    title: गति को धीमा करना
  - 
    title: बाधाएँ जोड़ना
  - 
    title: बाधाओं को अवरोध बनाना
  - 
    title: गेम का अंत बनाना
  - 
    title: बाधाएँ छुपाना
  - 
    title: फिनिश लाइन को तोड़ना
  - 
    title: आरंभ को सेट अप करना
  - 
    title: 'चुनौती: अपने ड्रम की पोशाक बदलें'
