---
title: Scratch Olympics Hurdler
hero_image: images / banner.png
description: A hurdler game in Scratch
original_url: https://raspberrypi.org/learning/scratch-olympics-hurdler
theme: narancs
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Getting hold of the sprites
  - 
    title: Setting up the assets
  - 
    title: Capturing the key mashing
  - 
    title: Animating the hurdler
  - 
    title: Jumping
  - 
    title: Slowing down
  - 
    title: Adding in hurdles
  - 
    title: Making the hurdles an obstacle
  - 
    title: Making an end to the game
  - 
    title: Hiding the hurdles
  - 
    title: Breaking the finish line
  - 
    title: Setting up the start
  - 
    title: What next?
