---
title: Scratch Olympics Hurdler
hero_image: images / banner.png
description: A hurdler game in Scratch
original_url: https://raspberrypi.org/learning/scratch-olympics-hurdler
theme: orange
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 2, 디자인 -0, 프로그래밍 -2, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: 게임
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: Getting hold of the sprites
  - 
    title: Setting up the assets
  - 
    title: Capturing the key mashing
  - 
    title: Animating the hurdler
  - 
    title: Jumping
  - 
    title: Slowing down
  - 
    title: Adding in hurdles
  - 
    title: Making the hurdles an obstacle
  - 
    title: Making an end to the game
  - 
    title: Hiding the hurdles
  - 
    title: Breaking the finish line
  - 
    title: Setting up the start
  - 
    title: '도전과제: 더 많은 연필들'
